---
title: "Rebecca N Assignment 9"
output: html_notebook
author: "Rebecca Neal"
date: "9 April 2020"
version: "2.0 - revised to clean up GitKraken"

---


Assignment 9 is utlizing ggplot2 for creating graphics

Load the tidyverse & ggplot2 package
```{r include=FALSE}
library(tidyverse)
library(ggplot2)
```

Load data
```{r include=FALSE}
SAD <- read_csv("Sexual Abuse Data.csv")
SAD
```

### Q1 Create a graph to compare PTSD scores of women who are abused and are not
```{r}
ggplot(SAD, aes(x = id, y = ptsd)) +
  geom_point(aes(color = csa))+
  labs(x = "Participant Number",
       y = "Post-traumatic Stress Disorder Scale",
       title = "PTSD Related to Childhood Sexual Abuse")
```

### Question 2 Create a graph to compare physical abuse scores of abused women
```{r}
ggplot(SAD, aes(x = id, y = cpa)) +
  geom_point(aes(color = csa))+
  labs(x = "Participant Number",
       y = "Childhood Physical Abuse Scale",
       title = "Childhood Physical Abuse Related to Childhood Sexual Abuse")
```

### Question 3 Plot and use different types of points and colors to seperate
```{r}
ggplot(SAD, aes(x = cpa, y = ptsd, color = csa)) +
  geom_point()+
  stat_smooth(method = "lm", se = FALSE)+
  labs(x = "Childhood Physical Abuse Scale",
       y = "Post-traumatic Stress Disorder Scale",
       title = "Childhood Physical Abuse Related to PTSD")
```










